### PR TITLE
Custom generator support added

### PR DESCRIPTION
**Pull request by xc0d3rz**
Now you can create your own generator or use it as callback

### CODE REVIEW

**Comment by csells** [comment]
is there a test of this support or an example of its use?

**Comment by xc0d3rz** [comment]
@csells No test file, but I'm working in example for its use

**Comment by xc0d3rz** [comment]
@csells Added, P.S Merge 😄

**Comment by NickCarneiro** [comment]
@xc0d3rz can you explain the purpose of this?

**Pull request closed without merging**
