### PR TITLE
ADD browser generator

### PR DESCRIPTION
**Pull request by RecuencoJones**
Thought it would be useful to have an equivalent for JavaScript in the browser 😄

### CODE REVIEW

**Comment by NickCarneiro** [comment]
Great contribution!

Watch out, the jQuery gang might want to come after you. ;)

I'll try to get this merged in tonight.

**Comment by RecuencoJones** [comment]
Thanks @NickCarneiro!

Just spotted a typo, I'll be able to fix tomorrow (`atob` should be `btoa` 😅)

**Comment by RecuencoJones** [comment]
It's fixed now @NickCarneiro

**Comment by NickCarneiro** [comment]
This is now live on the site. Give it a try! 

(May need a hard refresh)

**Comment by RecuencoJones** [comment]
Did a quick test and seems to be mapping to Python instead of fetch ☹️

**Comment by NickCarneiro** [comment]
Missed a line. Fixed now.

**Pull request merged**
