### PR TITLE
add ansible

### PR DESCRIPTION
**Pull request by jgroom33**
add ansible language

### CODE REVIEW

**Comment by jgroom33** [comment]
resolve #127

**Comment by jgroom33** [comment]
@NickCarneiro is this good to merge?  does npm bump automatically?

**Comment by NickCarneiro** [comment]
> @NickCarneiro is this good to merge? does npm bump automatically?

I don't think it bumps the version but I just merged and published manually.

**Comment by NickCarneiro** [comment]
@cf512 Let's do some release management to get this on the site tomorrow.

**Comment by jgroom33** [comment]
Adding this to the Ansible plugin for VS Code
https://github.com/VSChina/vscode-ansible/pull/244

**Pull request merged**
