### PR TITLE
Fix single quotes issue with PHP

### PR DESCRIPTION
**Pull request by nashe**
Aloha,
That for what I came for: strings with single quotes to the PHP converter is creating a wrong output.

Maybe we should discuss about how you're making your test cases, to make it easier to contribute. What if you change the output for one of the languages (obsolete library, new version with parameters change…)? I think you'll have to re-generate the output for each test, which will be a real and useless pain. It's nearly always the same process between each converters, so maybe by refactoring it into functions and testing theses functions directly… 

At least, having the same test files for all the languages would be great.

### CODE REVIEW

**Comment by NickCarneiro** [comment]
I agree that it is a pain right now. 

I do not completely understand the improvement you are suggesting. Are you saying it would be better to execute the generated code and check that it performs the correct request?

**Comment by nashe** [comment]
Nope, I misspoke! I was thinking about splitting the converters in functions and writing unit tests for each function, rather than just relying only on functional testing. 

For the functional testing, I think it would be nice to all the input files tested against each converter (in opposite of the actual way, where each converter have different tests).

**Comment by NickCarneiro** [comment]
So basically there would be three test functions, one per language. Each test function loops over all the input files. To add a new case you would just add input and output text files.

**Comment by nashe** [comment]
Maybe https://github.com/doowb/converter/tree/master/test can give you ideas :)

**Pull request merged**
