### PR TITLE
Use tree-sitter for bash parsing

### LINKED ISSUE #277: Error with string content have ‘=’ in it
for example：

> --data-raw '{"message":"a plus b=1"}' 

then we get

> data = {
>   '{"message":"a plus b': '1"}'
> }

what we need under python3 is

> data = '{"message":"a plus b=1"}'

notice that the '{}'here is not needed and may cause an exception when post.

### PR DESCRIPTION
**Pull request by verhovsky**
instead of yargs.

This PR makes argument parsing more similar to curl's:
- you can omit the space between short options `-XPOST` and use multiple short options `-ABC` etc.
- you can shorten long options, e.g. `--sil` instead of `--silent`
- adds all of curl's current options by parsing its source code. if you try to use an unknown option, it errors
- handles `--` (end of flagged arguments)
- basic support for `--data-urlencode`
- more correct precedence rules for determining which HTTP method to use

and also
- adds support for ANSI C quoted strings

Closes #277 #267 #221 #207 #195 and works on #85

but I'm sure it opens many new ones. Notably I noticed this https://github.com/tree-sitter/tree-sitter-bash/issues/100 . Also note that this might make curlconverter more complicated to install because tree-sitter is a Rust project that's compiled to WASM.

### CODE REVIEW

**Comment by jgroom33** [comment]
The file changes in this are a bit extensive.
Changing from var to let is certainly appreciated. But imo, these types of changes should be in a separate PR so the decision can be made independently.

**Comment by verhovsky** [comment]
The changes in `elixir.js` were made by `standard --fix`. They're a separate commit and PRs aren't squashed so they should appear as a separate commit in `git blame`. The rest of the changes (using `import` etc.) were necessary to use top-level `await`, which is required for loading tree-sitter grammars. The other option was to make `util.parseCurlCommand` an `async` function, which is what I tried originally but I had issues with `tape` tests not running properly, because now `test.js` needs to use `async` immediately-invoked functions. 

I could split this up into multiple PR's, but this whole thing is complicated by the fact that curlconverter seems to be broken on master, I can't even `npm install` on Node 16, because something (dunno how to figure out *what*) tries to install an old `puppeteer` and that fails to install Chromium.

**Comment by jgroom33** [comment]
Keep up the good work.

**Comment by verhovsky** [comment]
I had to modify a few tests and some of the generators to get the last couple of tests to pass. 

`multiline_post_with_data` was wrong (the `-X GET` makes the request a `GET`, even though it has `--data`) but it was also failing because if there's no space before the backslash, tree-sitter's bash grammar tokenizes it wrong https://github.com/tree-sitter/tree-sitter-bash/issues/100 . It would be nice to undo my fix for that this is ever fixed upstream, I'm sure curlconverter's users will run into this.

Since `request.data` can no longer be anything but a string, I had to remove that check from most generators (yargs set it to `true` if you passed an empty string and I think it returns a number if an argument can be parsed as an int?). A bunch of the generators wrongly assume `request.data` is JSON if a string is passed in.

This PR opens the door for correctly differentiating between actual bash variables and raw `$` characters in strings, but currently those are just converted to `$text` in the string like before (see #252). We can do way more to report parsing errors now, down to the line/character but that'll have to be another PR.

**Comment by NickCarneiro** [comment]
This is looking pretty legendary, especially the option extraction. Big step forward for the project.

I will test it out a bit locally to get familiar with tree-sitter. Expect a merge tomorrow.

**Comment by ahlinc** [comment]
@verhovsky I've made PRs on the `tree-sitter-bash` upstream that would solve your issues. Feel free to ping me if something else would be need with the grammar. This is awesome project by the way :tada:

**Comment by verhovsky** [comment]
@ahlinc this isn't part of the bash grammar, but could you please add `childrenForFieldName` to the JS bindings https://github.com/tree-sitter/tree-sitter/issues/601 ? I wanted to use it to get all the `argument` nodes

https://github.com/NickCarneiro/curlconverter/blob/e3113a97494c825ce19cd1442489188bd045ed5c/util.js#L545-L547

to avoid an error if there are `variable_assignment` node(s) before the actual command, e.g.

```sh
MY_VAR=foo curl example.com
```

Apparently there's also methods that are available on the web but not in Node https://github.com/tree-sitter/node-tree-sitter/issues/68 ? I just saw that issue when I was googling for `childrenForFieldName`, I personally don't know if it's true because I haven't tried to run this code in a web browser yet, I've been testing my changes exclusively through Node. Anyway, it would be good if tree-sitter's JS bindings were complete.

**Pull request merged**
